services: 
  node:
    build: ./srcs
    container_name: transcendance
    restart: always
    volumes:
      - transcendance:/app
    ports:
      - "5173:5173"

volumes:
  transcendance:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/Desktop/portfolio_V1.0
      o: bind
